# Generated by Django 3.1.2 on 2021-05-01 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20201202_1936'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table='jobs',
        ),
    ]
