# Generated by Django 3.1.2 on 2021-05-01 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20210430_2009'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='job',
            table='job',
        ),
    ]
